title: Sirius Seminars
description: We have discussions & seminars related to what we do / want to do.
theme: minima
baseurl: ""
url: "https://diptarkadas.github.io"

# For minima theme navigation
header_pages:
  - upcoming.md
  - past.md
  - contact.md

# Optional: Custom navigation (if header_pages doesn't work)
navigation:
  - title: Home
    url: /
  - title: Upcoming Talks
    url: /upcoming.html
  - title: Past Talks
    url: /past.html
  - title: Contact
    url: /contact.html
