title: Sirius Seminars
description: We have discussions & seminars related to what we do / want to do.
theme: minima
baseurl: "/sirius"
url: "https://diptarkadas.github.io"

# For minima theme navigation
header_pages:
  - upcoming.md
  - past.md
  - contact.md
